# Site settings
title: Provence

clients:
  - id: france
    name: France Tourism
    link: https://uk.france.fr/en
  - id: provence
    name: Provence Tourist Board
    link: http://www.morethanprovence.com/en/

description: >
  From the golden shoreline of the Mediterranean to the picturesque, cool mountain climes, Provence is set to offer even the most experienced travellers a tale of the unexpected.

baseurl: "/provence" # the subpath of your site, e.g. /blog/
url: "http://mp.secretescapes.com" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [js/scripts.min.js]
sass:
    sass_dir: css
    style: compressed